### ISSUE TITLE
I found a way to add support for highlight on Windows

### ISSUE THREAD

**Issue by t0md3an** [haifenghuang/magpie#7]
@haifenghuang 

Colors in magpie does not works on windows:

```
magpie>> [1mlet[m
```

But I found a way to fix this. If you add this in the `main()` function in `main.go` (only for windows, on other platform there will be an error) then the colors will work:

```go
handle := syscall.Handle(os.Stdout.Fd())
kernel32DLL := syscall.NewLazyDLL("kernel32.dll")
setConsoleModeProc := kernel32DLL.NewProc("SetConsoleMode")
setConsoleModeProc.Call(uintptr(handle), 0x0001|0x0002|0x0004)
```

On windows it successfully compiled, but on Linux/Darwin/other:

```
undefined: syscall.Handle
undefined: syscall.NewLazyDLL
```

**I do not know how to make `go` compiler to compile this part of code only for windows because there is no preprocessor in golang (`#ifdef`).**

**Comment by haifenghuang** [comment]
Golang doesn't support preprocessor, but it does support build tags(like build options). In your `.go` file's head, add below comment:

```
+build windows
```

I already know the magpie REPL will not work on the old window's `cmd.exe`. On windows, I use `conemu` terminal, it can correctly show the color, so I will not bother write the windows part of the color highlight.

If you really want the color to work with the old window's `cmd.exe`, then on the `github`, there are lots of color repository which could work with windows. Since magpie is open source, you can add it to the code as you like using `pull request`.

**Comment by haifenghuang** [comment]
I just added the color support for window. You can have a look and try it.

**Comment by t0md3an** [comment]
@haifenghuang Now I can't compile it:

```
Building REPL...(magpie)
# github.com/peterh/liner
src/github.com/peterh/liner/highlighter.go:79:19: undefined: isInwinConsole
src/github.com/peterh/liner/highlighter.go:91:16: undefined: getConsoleTextAttr
src/github.com/peterh/liner/highlighter.go:430:3: undefined: setConsoleTextAttr
src/github.com/peterh/liner/highlighter.go:432:3: undefined: setConsoleTextAttr
```
